# Generated by Django 2.1.2 on 2018-10-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookguest',
            name='link',
            field=models.CharField(default=' ', max_length=60, null=True),
        ),
    ]
