# Generated by Django 2.1.2 on 2018-10-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0004_auto_20181023_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookguest',
            name='cashBrowser',
            field=models.TextField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='bookguest',
            name='textMessage',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
