# Generated by Django 2.1.2 on 2018-10-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0006_auto_20181023_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookguest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
