# Generated by Django 2.1.2 on 2018-10-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0009_auto_20181029_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookguest',
            name='img',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
