# Generated by Django 2.1.2 on 2018-10-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0012_auto_20181029_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookguest',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
