# Generated by Django 2.1.2 on 2018-10-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0014_auto_20181029_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookguest',
            name='img',
            field=models.ImageField(blank=True, height_field=150, upload_to='image', width_field=150),
        ),
    ]
