# Generated by Django 2.1.2 on 2018-10-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0015_auto_20181029_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookguest',
            name='img',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
